### ISSUE TITLE
请问可否发布到npm

### ISSUE THREAD

**Issue by ghost** [Emeryao/typed-we-app#1]
你好， vscode1.6以后可以支持npm包的typings， 可否将dt发布到npm呢。

**Comment by emeryao** [comment]
用typings install不是也挺好的嘛？
dt的话也可以 但是更新起来比较麻烦 我研究一下怎么搞@types

用typings可以保持最新哦

```
typings install github:Emeryao/typed-we-app -SG
```

**Comment by ghost** [comment]
嗯 谢谢

**Comment by emeryao** [comment]
@m927259903 dt上已经有了 npm上也有了 https://www.npmjs.com/package/@types/weapp-api
所以我就不搞了 😆 
我看了一下那个 应该也能用 看的出来那是一个js开发者写的 跟我的思路有点不一样 😆

**Comment by emeryao** [comment]
好吧 我还是自己发了一个 😆
```batch
npm install typed-we-app --save-dev
```
