### ISSUE TITLE
Report an error when declaring a variable with this.data

### ISSUE THREAD

**Issue by kaiye** [Emeryao/typed-we-app#17]
make a sample page.js
```javascript
// @ts-check

Page({
  data: {
    pageTop: -1,
    pageBottom: 0,
  },
  onLoad() {
    const { pageTop, pageBottom } = this.data;
    console.log(pageTop, pageBottom);
  },
});
```
It reports an error `Type 'Object' has no property 'pageTop' and no string index signature`.

![image](https://user-images.githubusercontent.com/344283/48117840-695d3f00-e2a5-11e8-9b92-e117245eef03.png)

Go to file `index.d.ts` line 53,  change the data type from `Object` to `any` will mute the error.
```javascript
interface PageParam {
        /**页面的初始数据 */
        data?: Object;
```
Is there a bug or I missed some configuration?

**Comment by emeryao** [comment]
there are no bugs or configurations you ever missed

the declaration file is targeted and only tested for a `TypeScript`  project instead of a `Javascript` one

**Comment by kaiye** [comment]
Thanks for pointing it out.
Could you please do this change to make it works in Javascript project with `// @ts-check`, or do you have any other suggestions to solve this problem?

**Comment by emeryao** [comment]
Why don't you just try to work with the awesome TypeScript

you can take my another [repo](https://github.com/Emeryao/we-app-typescript) as reference 

And sorry to say that I have no idea how can `// @ts-check` work with declaration files
 so it's kind of hard for me to meet your request

**Comment by kaiye** [comment]
Good to know, thanks
