### ISSUE TITLE
A rest parameter must be of an array type.

### ISSUE THREAD

**Issue by John0King** [Emeryao/typed-we-app#18]
@Emeryao 

A rest parameter must be of an array type.

![image](https://user-images.githubusercontent.com/13639146/48602160-2722b480-e9ad-11e8-925a-6ba9fa8f54c6.png)

**Comment by emeryao** [comment]
`VS Code` does not complain about that since the type of `any` is kind of wider over the type of `Array<any>` 

Is this a `warning` or `error` in your Visual Studio?

**Comment by emeryao** [comment]
published to npm with version `typed-we-app@1.7.0-update.7`  
you can update it after a while

**Comment by emeryao** [comment]
@John0King 
Could you please provide some information for my [question](https://github.com/Emeryao/typed-we-app/issues/18#issuecomment-439302424) above?

**Comment by John0King** [comment]
@Emeryao  
> Is this a warning or error in your Visual Studio?

Yes , It also show when I use command line `tsc` . ps: it's an error not a warning.

It maybe a  change of TypeScript 3.x  , and  `any` can be a `Array` but not must be a array, and if you actually implement a method , you will see it's clearly an error (you can not use your parameters)

```typescript
function foo(year:number,month:number,day:number)
function foo(dateStr:string)
function foo(...args:any){
    if(args.length == 3) // no intellisense   
    {
        ...
    }
}
```

-----------------------
And I want to suggeste a change of some callback definition

```typescript
declare function foo(callback:(x?:string)=>any)  // x can be null or undefined, anything can happen in callback

declare  function foo(setting:{ 
    success:(x:string)=>any, // x shouldn't be null ,because it a success callback
    fail:(err:any)=>any 
})  
```

https://github.com/Emeryao/typed-we-app/blob/49983d9cc739caf07c2edbc3a55e70f9d2bc387f/we-app.d.ts#L545-L551

https://github.com/Emeryao/typed-we-app/blob/49983d9cc739caf07c2edbc3a55e70f9d2bc387f/we-app.d.ts#L608-L620

https://github.com/Emeryao/typed-we-app/blob/49983d9cc739caf07c2edbc3a55e70f9d2bc387f/we-app.d.ts#L758-L760

and others

**Comment by emeryao** [comment]
Hi @John0King   
![image](https://user-images.githubusercontent.com/3591899/48632505-059ce980-e9fc-11e8-830a-0a227814d084.png)
I'm not facing any error with the codes above

can you provide some codes that the error occurred?

**Comment by emeryao** [comment]
```typescript
declare function foo(callback:(x?:string)=>any)  // x can be null or undefined, anything can happen in callback

declare  function foo(setting:{ 
    success:(x:string)=>any, // x shouldn't be null ,because it a success callback
    // 👆 so what if something happened in a success callback? 🤣 
    fail:(err:any)=>any 
})  
```

**Comment by John0King** [comment]
@Emeryao 
```log
PS C:\Users\my-user-name> tsc --version
Version 3.0.1
```
What's your typescript version ?

let me try vs code .
`tsconfig.json` is created by `tsc --init`
![image](https://user-images.githubusercontent.com/13639146/48654529-913c6780-ea48-11e8-8c6f-66101def0b27.png)


> // 👆 so what if something happened in a success callback? 🤣 

Well, that will be an error that should let develpers or the wechat team to know.

**Comment by emeryao** [comment]
my TypeScript version is `3.1.6`  and I pointed it out with a red arrow on the right bottom [here](https://github.com/Emeryao/typed-we-app/issues/18#issuecomment-439440576)  

This project is mainly a TypeScript declaration file a `.d.ts` instead of `.ts` file
so... just cannot reproduce the error with your codes above

**Comment by John0King** [comment]
In fact 
```
declare function foo(...args) :void  // default type of args is   any[]
```
