### ISSUE TITLE
A runtime for Coding wechat MiniProgram in strong type. 

### ISSUE THREAD

**Issue by John0King** [Emeryao/typed-we-app#19]
I have an idea for improve  the code experience by using the Typescript way.(inspired from Angular)

I created a runtime for adapter between wechat configuration object  and the class.

It just an experiment , and it indeed work.

https://github.com/John0King/typed-we-app/blob/typescript-runtime/runtimeSample/pages/index/index.ts

**Comment by emeryao** [comment]
Thank you for this issue 👍 
I'll take a look about that 😄

**Comment by John0King** [comment]
![image](https://user-images.githubusercontent.com/13639146/48683787-b9170100-ebe9-11e8-890e-67a6f13720a2.png)

How do you think about this ?

The Component part still need more things to work, but should not be so hard.

Do you want me to send a PR to your repo ?

**Comment by emeryao** [comment]
👍 
I think you should create another repo for it with a name like `we-app-runtime` or something instead of putting codes into this repo cause this one is focused on the declaration

**Comment by John0King** [comment]
@Emeryao   The runtime is optional , 
you do not need enable declarator as long as you not reference the `Runtime` class/function(even you reference  the runtime thing as long as you not use `declarator`  that still work, it's just plain javascript when you use it )

I use separate typescript project eg. project reference in the source.
and honestly , I don't know how to work with NPM(publishing package, wechat's special configuration)
