### ISSUE TITLE
suggestion to merge to official site

### ISSUE THREAD

**Issue by jhcao23** [Emeryao/typed-we-app#2]
Hi Emery,

I searched around Internet and found your definition is the best and the most updated!
Will you consider to merge this great work to the official typescript definition `DefinitelyTyped` collection: [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped), so that more developers could know your excellent work and contribute together?

thanks,
John

**Comment by emeryao** [comment]
Thank you for your issue @jhcao23 
There is already a WeApp declaration file called `weapp-api` in the DefinitelyTyped repo, and I will file an issue there to check out if there is a  possibility to make my repo into it.
BTW, I also publish this repo to npm and you can get it via
```
npm install typed-we-app --save-dev
```

**Comment by jhcao23** [comment]
`weapp-api` is updated for a while. I prefer yours to go into it! You can simply create a PR there and the team will respond to you quickly!

**Comment by emeryao** [comment]
After much deliberation, I decided not to put my repo into `DefinitelyTyped` cause I think that will makes it out of my control and difficult for me to make further updates.
So just use my repo from npm if you like. 
Thanks for your issue 😄
