### ISSUE TITLE
How to return never when code uploadFile task onProgressUpdate callback function

### ISSUE THREAD

**Issue by memstone** [Emeryao/typed-we-app#9]
```javascript
function uploadFile(url: string, filePath: string, progress?: (progress: number) => never):Promise<{id:number,errMsg?:string}> {
    return new Promise<{id:number,errMsg?:string}>((resolve, reject) => {
        const uploadTask = wx.uploadFile({
            url: url,
            filePath: filePath,
            name: 'resourceFile',
            success: res => resolve(res),
            fail: e => reject(e)
        });
        if (progress){
        uploadTask.onProgressUpdate =
            (res: { progress: number; totalBytesSent: number; totalBytesExpectedToSend: number; }): never => {
                return progress(res.progress)
            }
        }
    });
}

function updateFileUploadProgress(progress:number):never{
    // do something
    return never
}
async function post2sever(page: IPage, images: { path: string }[]) {
    try {
        let fileIDs:Array<number> = new Array<number>()
        for (let img of images) {
            let res = await uploadFile('/resource', img.path, updateFileUploadProgress)
            if (res.errMsg) throw new Error(`upload image[${img.path}] occurs error:${res.errMsg}`)
            fileIDs.push(res.id);
        }
    } catch{

    }
}
```

bellow function how to retun never? must throw an error or use while true?
```javascript
function updateFileUploadProgress(progress:number):never{
    // do something
    return never
}
```

**Comment by emeryao** [comment]
> wrong comment deleted

**Comment by memstone** [comment]
It doesn't work.
error message: [ts] A function returning 'never' cannot have a reachable end point.

test and confirm please, thanks.

**Comment by Emeryao** [comment]
as your function `updateFileUploadProgress` has a return type of `never` so you just can't pass it as a parameter to another function call

**Comment by emeryao** [comment]
why don't you just google that error message and `test and confirm please` yourself ?

**Comment by memstone** [comment]
Yes, I do it.
But I think you point about never is wrong. you mean is void, not never.
never function can assign to type of never variables. But a function without return, it's type is void, not never. you should throw an error or user while true. Because never mean never return.

When I remove return never, tsc tell me, "A function returning 'never' cannot have a reachable end point."(an empty file only add function "updateFileUploadProgress"), function declare type and function implement type incompatible!
